
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
args.model_config: /home/hslee/FINE-FPN/new_ultralytics/ultralytics/cfg/models/v10/yolov10l_FINE.yaml
args.model_config: /home/hslee/FINE-FPN/new_ultralytics/ultralytics/cfg/models/v10/yolov10l_FINE.yaml
args.model_config: /home/hslee/FINE-FPN/new_ultralytics/ultralytics/cfg/models/v10/yolov10l_FINE.yaml
args.model_config: /home/hslee/FINE-FPN/new_ultralytics/ultralytics/cfg/models/v10/yolov10l_FINE.yaml
YOLOv10l_FINE summary: 400 layers, 28,917,200 parameters, 28,917,184 gradients, 130.7 GFLOPs
Ultralytics 8.3.159 ðŸš€ Python-3.11.13 torch-2.7.1+cu128 CUDA:0 (NVIDIA GeForce RTX 5090, 32120MiB)
                                                        CUDA:1 (NVIDIA GeForce RTX 5090, 32120MiB)
                                                        CUDA:2 (NVIDIA GeForce RTX 5090, 32117MiB)
                                                        CUDA:3 (NVIDIA GeForce RTX 5090, 32120MiB)
Freezing layer 'model.21.dfl.conv.weight'
[34m[1mAMP: [0mrunning Automatic Mixed Precision (AMP) checks...
[34m[1mAMP: [0mchecks passed âœ…
[rank2]:[W715 13:44:13.113725253 CUDAGuardImpl.h:119] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank0]:[W715 13:44:13.156399704 CUDAGuardImpl.h:119] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank3]:[W715 13:44:13.156630551 CUDAGuardImpl.h:119] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
[rank1]:[W715 13:44:13.157859602 CUDAGuardImpl.h:119] Warning: CUDA warning: an illegal memory access was encountered (function destroyEvent)
W0715 13:44:14.655000 71265 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 71341 closing signal SIGTERM
W0715 13:44:14.655000 71265 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 71342 closing signal SIGTERM
W0715 13:44:14.655000 71265 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 71344 closing signal SIGTERM
E0715 13:44:17.800000 71265 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: -6) local_rank: 2 (pid: 71343) of binary: /home/hslee/anaconda3/envs/torch271/bin/python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/hslee/anaconda3/envs/torch271/lib/python3.11/site-packages/torch/distributed/run.py", line 896, in <module>
    main()
  File "/home/hslee/anaconda3/envs/torch271/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/envs/torch271/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/hslee/anaconda3/envs/torch271/lib/python3.11/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/hslee/anaconda3/envs/torch271/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hslee/anaconda3/envs/torch271/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
train.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-15_13:44:14
  host      : black
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 71343)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 71343
======================================================
