Traceback (most recent call last):
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/__init__.py", line 295, in _load_global_deps
    ctypes.CDLL(global_deps_lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libnvToolsExt.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hslee/CLASS-FPN/new_ultralytics/export_trt.py", line 1, in <module>
    from ultralytics import YOLO
  File "/home/hslee/CLASS-FPN/new_ultralytics/ultralytics/__init__.py", line 11, in <module>
    from ultralytics.models import NAS, RTDETR, SAM, YOLO, YOLOE, FastSAM, YOLOWorld
  File "/home/hslee/CLASS-FPN/new_ultralytics/ultralytics/models/__init__.py", line 3, in <module>
    from .fastsam import FastSAM
  File "/home/hslee/CLASS-FPN/new_ultralytics/ultralytics/models/fastsam/__init__.py", line 3, in <module>
    from .model import FastSAM
  File "/home/hslee/CLASS-FPN/new_ultralytics/ultralytics/models/fastsam/model.py", line 6, in <module>
    from ultralytics.engine.model import Model
  File "/home/hslee/CLASS-FPN/new_ultralytics/ultralytics/engine/model.py", line 8, in <module>
    import torch
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/__init__.py", line 360, in <module>
    _load_global_deps()
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/__init__.py", line 318, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/hslee/.local/lib/python3.10/site-packages/torch/__init__.py", line 279, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/hslee/CLASS-FPN/new_ultralytics', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '/home/hslee/.local/lib/python3.10/site-packages', '__editable__.ultralytics-8.3.94.finder.__path_hook__', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/lib/python3.10/dist-packages']
